### ISSUE TITLE
IDEK whats going on

### ISSUE THREAD

**Issue by Joschels** [Luois45/SkinbaronBot_v2#18]
![image](https://github.com/Luois45/SkinbaronBot_v2/assets/146980520/2464fd95-5ba2-4889-aacf-93c294f816ae)

![image](https://github.com/Luois45/SkinbaronBot_v2/assets/146980520/fc361d44-b275-444c-b3a5-78fbc0a8d7d9)

**Comment by Joschels** [comment]
pls help

**Comment by Joschels** [comment]
solved the first but got this now, cannot buy anything with this error:
![image](https://github.com/Luois45/SkinbaronBot_v2/assets/146980520/f6d133d0-f091-4060-91b1-113c41fc52bf)

**Comment by Luois45** [comment]
the config.json file must be in the folder you're running python from
